spring:
  jpa:
    database: H2
    hibernate:
      ddl-auto: create-drop
      use-new-id-generator-mappings: true
    show-sql: true
    properties:
      hibernate.format_sql: true
    generate-ddl: true

logging:
  level:
    org:
      hibernate:
        type: trace