#spring:
#    jpa:
#      database: mysql
#datasource:url=jdbc:mysql://localhost:3306/todo?useUnicode=true&characterEncoding=utf8
#spring.datasource.username=root
#spring.datasource.password=
#spring.datasource.driver-class-name=com.mysql.jdbc.Driver
#
##logging.level.org.springframework.web: DEBUG
#spring.jpa.hibernate.ddl-auto=create-drop
#logging.level.org.hibernate.SQL=DEBUG
#logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

spring:
  jpa:
    database: mysql
    hibernate:
      ddl-auto: create-drop
      use-new-id-generator-mappings: true
    show-sql: true
    properties:
      hibernate.format_sql: true
    generate-ddl: true
#    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

  datasource:
    platform: mysql
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/todo?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false
    username: root
    password:
#
logging:
  level:
    org:
      hibernate:
        type: trace